version: 2
jobs:
  test-and-build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/gogen
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            go get -t ./...
            go get github.com/onsi/ginkgo/ginkgo

      - run:
          name: Run unit tests
          command: |
            ginkgo -r

      - run:
          name: Build mac executable
          command: |
            echo "Hello, world!" > echo-output


      - run:
          name: Build windows executable
          command: |
            echo "Skipped"

      - run:
          name: Build test data generator
          command: |
            echo "Skipped"

      - persist_to_workspace:
          root: '.'
          paths:
            - echo-output

  deploy:
    docker:
      - image: cibuilds/github:0.10

  - attach_workspace:
      at: ./artifacts

    steps:
      - run: |
          if [[ `cat ./artifacts/echo-output` == "Hello, world!" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  version: 2
  build-workflow:
    jobs:
      - test-and-build
      - hold:
          type: approval
          requires:
            - test-and-build
      - deploy:
          requires:
            - hold
