version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/gogen
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            go get -t ./...
            go get github.com/onsi/ginkgo/ginkgo

      - run:
          name: Run unit tests
          environment:

          command: |
            ginkgo -r

  deploy:
    docker:
      - image: circleci/golang:1.12

    steps:
      - run:
        command: |
          echo "Deployed"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
