version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    parallelism: 2 # TODO

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

#      - restore_cache:
#          keys:
#            - go-mod-v4-{{ checksum "go.sum" }}

      - run:
          name: install dependencies
          command: |
            go get ./...
            go get github.com/onsi/ginkgo/ginkgo
            go get -t ./...


      - run:
          name: Run unit tests
          environment:

          command: |
            ginkgo -r

#      - save_cache:
#          key: go-mod-v4-{{ checksum "go.sum" }}
#          paths:
#            - "/go/pkg/mod"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
